import type { Graph } from "./graph";
import type { Edge } from "./edge";
import type { Node } from "./node";

function escapeVcg(text: string): string {
  return text.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function formatVcgValue(value: string): string {
  const escaped = escapeVcg(value);
  if (/^\d+$/.test(escaped)) return escaped;
  return `"${escaped}"`;
}

function graphTitle(graph: Graph): string | undefined {
  const title = graph.graphAttributes.title ?? graph.graphAttributes.label;
  return title !== undefined && title !== "" ? title : undefined;
}

function nodeAttributes(node: Node): Record<string, string> {
  const attrs: Record<string, string> = { ...node.attributes };
  attrs.title = node.id;
  if (attrs.label === undefined && node.label !== node.id) {
    attrs.label = node.label;
  }
  return attrs;
}

function edgeAttributes(edge: Edge): Record<string, string> {
  const attrs: Record<string, string> = { ...edge.attributes };
  attrs.sourcename = edge.from.id;
  attrs.targetname = edge.to.id;
  if (attrs.label === undefined && edge.label) {
    attrs.label = edge.label;
  }
  if (edge.undirected) {
    attrs.arrowhead = "none";
    attrs.arrowtail = "none";
  }
  return attrs;
}

function attributesToBlock(attrs: Record<string, string>): string {
  const parts: string[] = [];
  for (const key of Object.keys(attrs).sort()) {
    const value = attrs[key];
    if (value === undefined || value === "") continue;
    parts.push(`${key}: ${formatVcgValue(value)}`);
  }
  if (parts.length === 0) return "";
  return `{ ${parts.join(" ")} }`;
}

function sortedNodes(graph: Graph): Node[] {
  return [...graph.nodes()].sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
}

function sortedEdges(graph: Graph): Edge[] {
  return [...graph.edges].sort((a, b) => a.id - b.id);
}

export function renderVcg(graph: Graph): string {
  const lines: string[] = [];
  lines.push("graph: {");

  const title = graphTitle(graph);
  if (title) lines.push(`  title: ${formatVcgValue(title)}`);

  const now = new Date().toString();
  lines.push(`\n  // Generated by graph-easy-ts at ${now}`);

  for (const node of sortedNodes(graph)) {
    const attrs = attributesToBlock(nodeAttributes(node));
    lines.push(`  node: ${attrs || "{ }"}`);
  }

  for (const edge of sortedEdges(graph)) {
    const attrs = attributesToBlock(edgeAttributes(edge));
    lines.push(`  edge: ${attrs || "{ }"}`);
  }

  lines.push("}\n");
  return lines.join("\n");
}
